/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as OgDotpngRouteImport } from './routes/og[.]png'
import { Route as OrgsRouteRouteImport } from './routes/orgs/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as loggedInRouteRouteImport } from './routes/(logged-in)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgsIndexRouteImport } from './routes/orgs/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrgsOrgSlugRouteRouteImport } from './routes/orgs/$orgSlug/route'
import { Route as AppTicketsRouteRouteImport } from './routes/app/tickets/route'
import { Route as AppQuotationsRouteRouteImport } from './routes/app/quotations/route'
import { Route as AppPurchaseOrdersRouteRouteImport } from './routes/app/purchase-orders/route'
import { Route as AppProductsRouteRouteImport } from './routes/app/products/route'
import { Route as AppInvoicesRouteRouteImport } from './routes/app/invoices/route'
import { Route as AppInsightsRouteRouteImport } from './routes/app/insights/route'
import { Route as AppDeliveryFormsRouteRouteImport } from './routes/app/delivery-forms/route'
import { Route as AppClientsRouteRouteImport } from './routes/app/clients/route'
import { Route as loggedInAccountRouteRouteImport } from './routes/(logged-in)/account/route'
import { Route as OrgsNewIndexRouteImport } from './routes/orgs/new/index'
import { Route as OrgsListIndexRouteImport } from './routes/orgs/list/index'
import { Route as AuthVerifyIndexRouteImport } from './routes/auth/verify/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'
import { Route as AuthNewUserIndexRouteImport } from './routes/auth/new-user/index'
import { Route as AuthGoodbyeIndexRouteImport } from './routes/auth/goodbye/index'
import { Route as AuthForgetPasswordIndexRouteImport } from './routes/auth/forget-password/index'
import { Route as AuthConfirmDeleteIndexRouteImport } from './routes/auth/confirm-delete/index'
import { Route as AppTicketsIndexRouteImport } from './routes/app/tickets/index'
import { Route as AppQuotationsIndexRouteImport } from './routes/app/quotations/index'
import { Route as AppPurchaseOrdersIndexRouteImport } from './routes/app/purchase-orders/index'
import { Route as AppProductsIndexRouteImport } from './routes/app/products/index'
import { Route as AppInvoicesIndexRouteImport } from './routes/app/invoices/index'
import { Route as AppInsightsIndexRouteImport } from './routes/app/insights/index'
import { Route as AppDeliveryFormsIndexRouteImport } from './routes/app/delivery-forms/index'
import { Route as AppClientsIndexRouteImport } from './routes/app/clients/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations/index'
import { Route as loggedInAccountIndexRouteImport } from './routes/(logged-in)/account/index'
import { Route as AppTicketsNewRouteImport } from './routes/app/tickets/new'
import { Route as AppQuotationsNewRouteImport } from './routes/app/quotations/new'
import { Route as AppPurchaseOrdersNewRouteImport } from './routes/app/purchase-orders/new'
import { Route as AppInvoicesNewRouteImport } from './routes/app/invoices/new'
import { Route as AppDeliveryFormsNewRouteImport } from './routes/app/delivery-forms/new'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OrgsOrgSlugnavigationRouteRouteImport } from './routes/orgs/$orgSlug/(navigation)/route'
import { Route as OrgsAcceptInvitationIdIndexRouteImport } from './routes/orgs/accept-invitation/$id/index'
import { Route as OrgsOrgSlugnavigationIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/index'
import { Route as AuthSigninOtpIndexRouteImport } from './routes/auth/signin/otp/index'
import { Route as AppTicketsTicketIdIndexRouteImport } from './routes/app/tickets/$ticketId/index'
import { Route as AppQuotationsQuotationIdIndexRouteImport } from './routes/app/quotations/$quotationId/index'
import { Route as AppPurchaseOrdersPurchaseOrderIdIndexRouteImport } from './routes/app/purchase-orders/$purchaseOrderId/index'
import { Route as AppProductsProductIdIndexRouteImport } from './routes/app/products/$productId/index'
import { Route as AppInvoicesInvoiceIdIndexRouteImport } from './routes/app/invoices/$invoiceId/index'
import { Route as AppDeliveryFormsDeliveryFormIdIndexRouteImport } from './routes/app/delivery-forms/$deliveryFormId/index'
import { Route as AppClientsClientIdIndexRouteImport } from './routes/app/clients/$clientId/index'
import { Route as AdminUsersUserIdIndexRouteImport } from './routes/admin/users/$userId/index'
import { Route as AdminOrganizationsOrgIdIndexRouteImport } from './routes/admin/organizations/$orgId/index'
import { Route as loggedInAccountSecurityIndexRouteImport } from './routes/(logged-in)/account/security/index'
import { Route as loggedInAccountDangerIndexRouteImport } from './routes/(logged-in)/account/danger/index'
import { Route as loggedInAccountChangePasswordIndexRouteImport } from './routes/(logged-in)/account/change-password/index'
import { Route as loggedInAccountChangeEmailIndexRouteImport } from './routes/(logged-in)/account/change-email/index'
import { Route as OrgsOrgSlugnavigationSettingsRouteRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/route'
import { Route as OrgsOrgSlugnavigationSettingsIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/index'
import { Route as OrgsOrgSlugnavigationDemoIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/demo/index'
import { Route as loggedInAccountSecurityNewPasswordIndexRouteImport } from './routes/(logged-in)/account/security/new-password/index'
import { Route as ApiAdminOrganizationsOrgIdPaymentsRouteImport } from './routes/api/admin/organizations/$orgId/payments'
import { Route as OrgsOrgSlugnavigationSettingsMembersIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/members/index'
import { Route as OrgsOrgSlugnavigationSettingsDangerIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/danger/index'

const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotpngRoute = OgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsRouteRoute = OrgsRouteRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const loggedInRouteRoute = loggedInRouteRouteImport.update({
  id: '/(logged-in)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgsRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrgsOrgSlugRouteRoute = OrgsOrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => OrgsRouteRoute,
} as any)
const AppTicketsRouteRoute = AppTicketsRouteRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuotationsRouteRoute = AppQuotationsRouteRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPurchaseOrdersRouteRoute = AppPurchaseOrdersRouteRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsRouteRoute = AppProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvoicesRouteRoute = AppInvoicesRouteRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInsightsRouteRoute = AppInsightsRouteRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeliveryFormsRouteRoute = AppDeliveryFormsRouteRouteImport.update({
  id: '/delivery-forms',
  path: '/delivery-forms',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsRouteRoute = AppClientsRouteRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRouteRoute,
} as any)
const loggedInAccountRouteRoute = loggedInAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => loggedInRouteRoute,
} as any)
const OrgsNewIndexRoute = OrgsNewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => OrgsRouteRoute,
} as any)
const OrgsListIndexRoute = OrgsListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => OrgsRouteRoute,
} as any)
const AuthVerifyIndexRoute = AuthVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthNewUserIndexRoute = AuthNewUserIndexRouteImport.update({
  id: '/new-user/',
  path: '/new-user/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthGoodbyeIndexRoute = AuthGoodbyeIndexRouteImport.update({
  id: '/goodbye/',
  path: '/goodbye/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgetPasswordIndexRoute = AuthForgetPasswordIndexRouteImport.update({
  id: '/forget-password/',
  path: '/forget-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthConfirmDeleteIndexRoute = AuthConfirmDeleteIndexRouteImport.update({
  id: '/confirm-delete/',
  path: '/confirm-delete/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppTicketsIndexRoute = AppTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTicketsRouteRoute,
} as any)
const AppQuotationsIndexRoute = AppQuotationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQuotationsRouteRoute,
} as any)
const AppPurchaseOrdersIndexRoute = AppPurchaseOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPurchaseOrdersRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInvoicesRouteRoute,
} as any)
const AppInsightsIndexRoute = AppInsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInsightsRouteRoute,
} as any)
const AppDeliveryFormsIndexRoute = AppDeliveryFormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDeliveryFormsRouteRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const loggedInAccountIndexRoute = loggedInAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => loggedInAccountRouteRoute,
} as any)
const AppTicketsNewRoute = AppTicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTicketsRouteRoute,
} as any)
const AppQuotationsNewRoute = AppQuotationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppQuotationsRouteRoute,
} as any)
const AppPurchaseOrdersNewRoute = AppPurchaseOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPurchaseOrdersRouteRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppInvoicesRouteRoute,
} as any)
const AppDeliveryFormsNewRoute = AppDeliveryFormsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDeliveryFormsRouteRoute,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgSlugnavigationRouteRoute =
  OrgsOrgSlugnavigationRouteRouteImport.update({
    id: '/(navigation)',
    getParentRoute: () => OrgsOrgSlugRouteRoute,
  } as any)
const OrgsAcceptInvitationIdIndexRoute =
  OrgsAcceptInvitationIdIndexRouteImport.update({
    id: '/accept-invitation/$id/',
    path: '/accept-invitation/$id/',
    getParentRoute: () => OrgsRouteRoute,
  } as any)
const OrgsOrgSlugnavigationIndexRoute =
  OrgsOrgSlugnavigationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgsOrgSlugnavigationRouteRoute,
  } as any)
const AuthSigninOtpIndexRoute = AuthSigninOtpIndexRouteImport.update({
  id: '/signin/otp/',
  path: '/signin/otp/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppTicketsTicketIdIndexRoute = AppTicketsTicketIdIndexRouteImport.update({
  id: '/$ticketId/',
  path: '/$ticketId/',
  getParentRoute: () => AppTicketsRouteRoute,
} as any)
const AppQuotationsQuotationIdIndexRoute =
  AppQuotationsQuotationIdIndexRouteImport.update({
    id: '/$quotationId/',
    path: '/$quotationId/',
    getParentRoute: () => AppQuotationsRouteRoute,
  } as any)
const AppPurchaseOrdersPurchaseOrderIdIndexRoute =
  AppPurchaseOrdersPurchaseOrderIdIndexRouteImport.update({
    id: '/$purchaseOrderId/',
    path: '/$purchaseOrderId/',
    getParentRoute: () => AppPurchaseOrdersRouteRoute,
  } as any)
const AppProductsProductIdIndexRoute =
  AppProductsProductIdIndexRouteImport.update({
    id: '/$productId/',
    path: '/$productId/',
    getParentRoute: () => AppProductsRouteRoute,
  } as any)
const AppInvoicesInvoiceIdIndexRoute =
  AppInvoicesInvoiceIdIndexRouteImport.update({
    id: '/$invoiceId/',
    path: '/$invoiceId/',
    getParentRoute: () => AppInvoicesRouteRoute,
  } as any)
const AppDeliveryFormsDeliveryFormIdIndexRoute =
  AppDeliveryFormsDeliveryFormIdIndexRouteImport.update({
    id: '/$deliveryFormId/',
    path: '/$deliveryFormId/',
    getParentRoute: () => AppDeliveryFormsRouteRoute,
  } as any)
const AppClientsClientIdIndexRoute = AppClientsClientIdIndexRouteImport.update({
  id: '/$clientId/',
  path: '/$clientId/',
  getParentRoute: () => AppClientsRouteRoute,
} as any)
const AdminUsersUserIdIndexRoute = AdminUsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsOrgIdIndexRoute =
  AdminOrganizationsOrgIdIndexRouteImport.update({
    id: '/organizations/$orgId/',
    path: '/organizations/$orgId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const loggedInAccountSecurityIndexRoute =
  loggedInAccountSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => loggedInAccountRouteRoute,
  } as any)
const loggedInAccountDangerIndexRoute =
  loggedInAccountDangerIndexRouteImport.update({
    id: '/danger/',
    path: '/danger/',
    getParentRoute: () => loggedInAccountRouteRoute,
  } as any)
const loggedInAccountChangePasswordIndexRoute =
  loggedInAccountChangePasswordIndexRouteImport.update({
    id: '/change-password/',
    path: '/change-password/',
    getParentRoute: () => loggedInAccountRouteRoute,
  } as any)
const loggedInAccountChangeEmailIndexRoute =
  loggedInAccountChangeEmailIndexRouteImport.update({
    id: '/change-email/',
    path: '/change-email/',
    getParentRoute: () => loggedInAccountRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsRouteRoute =
  OrgsOrgSlugnavigationSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrgsOrgSlugnavigationRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsIndexRoute =
  OrgsOrgSlugnavigationSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsRouteRoute,
  } as any)
const OrgsOrgSlugnavigationDemoIndexRoute =
  OrgsOrgSlugnavigationDemoIndexRouteImport.update({
    id: '/demo/',
    path: '/demo/',
    getParentRoute: () => OrgsOrgSlugnavigationRouteRoute,
  } as any)
const loggedInAccountSecurityNewPasswordIndexRoute =
  loggedInAccountSecurityNewPasswordIndexRouteImport.update({
    id: '/security/new-password/',
    path: '/security/new-password/',
    getParentRoute: () => loggedInAccountRouteRoute,
  } as any)
const ApiAdminOrganizationsOrgIdPaymentsRoute =
  ApiAdminOrganizationsOrgIdPaymentsRouteImport.update({
    id: '/api/admin/organizations/$orgId/payments',
    path: '/api/admin/organizations/$orgId/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgsOrgSlugnavigationSettingsMembersIndexRoute =
  OrgsOrgSlugnavigationSettingsMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsDangerIndexRoute =
  OrgsOrgSlugnavigationSettingsDangerIndexRouteImport.update({
    id: '/danger/',
    path: '/danger/',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/orgs': typeof OrgsRouteRouteWithChildren
  '/og.png': typeof OgDotpngRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/account': typeof loggedInAccountRouteRouteWithChildren
  '/app/clients': typeof AppClientsRouteRouteWithChildren
  '/app/delivery-forms': typeof AppDeliveryFormsRouteRouteWithChildren
  '/app/insights': typeof AppInsightsRouteRouteWithChildren
  '/app/invoices': typeof AppInvoicesRouteRouteWithChildren
  '/app/products': typeof AppProductsRouteRouteWithChildren
  '/app/purchase-orders': typeof AppPurchaseOrdersRouteRouteWithChildren
  '/app/quotations': typeof AppQuotationsRouteRouteWithChildren
  '/app/tickets': typeof AppTicketsRouteRouteWithChildren
  '/orgs/$orgSlug': typeof OrgsOrgSlugnavigationRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/app/delivery-forms/new': typeof AppDeliveryFormsNewRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/app/quotations/new': typeof AppQuotationsNewRoute
  '/app/tickets/new': typeof AppTicketsNewRoute
  '/account/': typeof loggedInAccountIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/delivery-forms/': typeof AppDeliveryFormsIndexRoute
  '/app/insights/': typeof AppInsightsIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/app/quotations/': typeof AppQuotationsIndexRoute
  '/app/tickets/': typeof AppTicketsIndexRoute
  '/auth/confirm-delete/': typeof AuthConfirmDeleteIndexRoute
  '/auth/forget-password/': typeof AuthForgetPasswordIndexRoute
  '/auth/goodbye/': typeof AuthGoodbyeIndexRoute
  '/auth/new-user/': typeof AuthNewUserIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify/': typeof AuthVerifyIndexRoute
  '/orgs/list/': typeof OrgsListIndexRoute
  '/orgs/new/': typeof OrgsNewIndexRoute
  '/orgs/$orgSlug/settings': typeof OrgsOrgSlugnavigationSettingsRouteRouteWithChildren
  '/account/change-email/': typeof loggedInAccountChangeEmailIndexRoute
  '/account/change-password/': typeof loggedInAccountChangePasswordIndexRoute
  '/account/danger/': typeof loggedInAccountDangerIndexRoute
  '/account/security/': typeof loggedInAccountSecurityIndexRoute
  '/admin/organizations/$orgId/': typeof AdminOrganizationsOrgIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/app/clients/$clientId/': typeof AppClientsClientIdIndexRoute
  '/app/delivery-forms/$deliveryFormId/': typeof AppDeliveryFormsDeliveryFormIdIndexRoute
  '/app/invoices/$invoiceId/': typeof AppInvoicesInvoiceIdIndexRoute
  '/app/products/$productId/': typeof AppProductsProductIdIndexRoute
  '/app/purchase-orders/$purchaseOrderId/': typeof AppPurchaseOrdersPurchaseOrderIdIndexRoute
  '/app/quotations/$quotationId/': typeof AppQuotationsQuotationIdIndexRoute
  '/app/tickets/$ticketId/': typeof AppTicketsTicketIdIndexRoute
  '/auth/signin/otp/': typeof AuthSigninOtpIndexRoute
  '/orgs/$orgSlug/': typeof OrgsOrgSlugnavigationIndexRoute
  '/orgs/accept-invitation/$id/': typeof OrgsAcceptInvitationIdIndexRoute
  '/api/admin/organizations/$orgId/payments': typeof ApiAdminOrganizationsOrgIdPaymentsRoute
  '/account/security/new-password/': typeof loggedInAccountSecurityNewPasswordIndexRoute
  '/orgs/$orgSlug/demo/': typeof OrgsOrgSlugnavigationDemoIndexRoute
  '/orgs/$orgSlug/settings/': typeof OrgsOrgSlugnavigationSettingsIndexRoute
  '/orgs/$orgSlug/settings/danger/': typeof OrgsOrgSlugnavigationSettingsDangerIndexRoute
  '/orgs/$orgSlug/settings/members/': typeof OrgsOrgSlugnavigationSettingsMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/og.png': typeof OgDotpngRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/orgs/$orgSlug': typeof OrgsOrgSlugnavigationIndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/orgs': typeof OrgsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/app/delivery-forms/new': typeof AppDeliveryFormsNewRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/app/quotations/new': typeof AppQuotationsNewRoute
  '/app/tickets/new': typeof AppTicketsNewRoute
  '/account': typeof loggedInAccountIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/delivery-forms': typeof AppDeliveryFormsIndexRoute
  '/app/insights': typeof AppInsightsIndexRoute
  '/app/invoices': typeof AppInvoicesIndexRoute
  '/app/products': typeof AppProductsIndexRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersIndexRoute
  '/app/quotations': typeof AppQuotationsIndexRoute
  '/app/tickets': typeof AppTicketsIndexRoute
  '/auth/confirm-delete': typeof AuthConfirmDeleteIndexRoute
  '/auth/forget-password': typeof AuthForgetPasswordIndexRoute
  '/auth/goodbye': typeof AuthGoodbyeIndexRoute
  '/auth/new-user': typeof AuthNewUserIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/verify': typeof AuthVerifyIndexRoute
  '/orgs/list': typeof OrgsListIndexRoute
  '/orgs/new': typeof OrgsNewIndexRoute
  '/account/change-email': typeof loggedInAccountChangeEmailIndexRoute
  '/account/change-password': typeof loggedInAccountChangePasswordIndexRoute
  '/account/danger': typeof loggedInAccountDangerIndexRoute
  '/account/security': typeof loggedInAccountSecurityIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
  '/app/clients/$clientId': typeof AppClientsClientIdIndexRoute
  '/app/delivery-forms/$deliveryFormId': typeof AppDeliveryFormsDeliveryFormIdIndexRoute
  '/app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdIndexRoute
  '/app/products/$productId': typeof AppProductsProductIdIndexRoute
  '/app/purchase-orders/$purchaseOrderId': typeof AppPurchaseOrdersPurchaseOrderIdIndexRoute
  '/app/quotations/$quotationId': typeof AppQuotationsQuotationIdIndexRoute
  '/app/tickets/$ticketId': typeof AppTicketsTicketIdIndexRoute
  '/auth/signin/otp': typeof AuthSigninOtpIndexRoute
  '/orgs/accept-invitation/$id': typeof OrgsAcceptInvitationIdIndexRoute
  '/api/admin/organizations/$orgId/payments': typeof ApiAdminOrganizationsOrgIdPaymentsRoute
  '/account/security/new-password': typeof loggedInAccountSecurityNewPasswordIndexRoute
  '/orgs/$orgSlug/demo': typeof OrgsOrgSlugnavigationDemoIndexRoute
  '/orgs/$orgSlug/settings': typeof OrgsOrgSlugnavigationSettingsIndexRoute
  '/orgs/$orgSlug/settings/danger': typeof OrgsOrgSlugnavigationSettingsDangerIndexRoute
  '/orgs/$orgSlug/settings/members': typeof OrgsOrgSlugnavigationSettingsMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(logged-in)': typeof loggedInRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/orgs': typeof OrgsRouteRouteWithChildren
  '/og.png': typeof OgDotpngRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/(logged-in)/account': typeof loggedInAccountRouteRouteWithChildren
  '/app/clients': typeof AppClientsRouteRouteWithChildren
  '/app/delivery-forms': typeof AppDeliveryFormsRouteRouteWithChildren
  '/app/insights': typeof AppInsightsRouteRouteWithChildren
  '/app/invoices': typeof AppInvoicesRouteRouteWithChildren
  '/app/products': typeof AppProductsRouteRouteWithChildren
  '/app/purchase-orders': typeof AppPurchaseOrdersRouteRouteWithChildren
  '/app/quotations': typeof AppQuotationsRouteRouteWithChildren
  '/app/tickets': typeof AppTicketsRouteRouteWithChildren
  '/orgs/$orgSlug': typeof OrgsOrgSlugRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/orgs/$orgSlug/(navigation)': typeof OrgsOrgSlugnavigationRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/app/delivery-forms/new': typeof AppDeliveryFormsNewRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/app/quotations/new': typeof AppQuotationsNewRoute
  '/app/tickets/new': typeof AppTicketsNewRoute
  '/(logged-in)/account/': typeof loggedInAccountIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/delivery-forms/': typeof AppDeliveryFormsIndexRoute
  '/app/insights/': typeof AppInsightsIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/app/quotations/': typeof AppQuotationsIndexRoute
  '/app/tickets/': typeof AppTicketsIndexRoute
  '/auth/confirm-delete/': typeof AuthConfirmDeleteIndexRoute
  '/auth/forget-password/': typeof AuthForgetPasswordIndexRoute
  '/auth/goodbye/': typeof AuthGoodbyeIndexRoute
  '/auth/new-user/': typeof AuthNewUserIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify/': typeof AuthVerifyIndexRoute
  '/orgs/list/': typeof OrgsListIndexRoute
  '/orgs/new/': typeof OrgsNewIndexRoute
  '/orgs/$orgSlug/(navigation)/settings': typeof OrgsOrgSlugnavigationSettingsRouteRouteWithChildren
  '/(logged-in)/account/change-email/': typeof loggedInAccountChangeEmailIndexRoute
  '/(logged-in)/account/change-password/': typeof loggedInAccountChangePasswordIndexRoute
  '/(logged-in)/account/danger/': typeof loggedInAccountDangerIndexRoute
  '/(logged-in)/account/security/': typeof loggedInAccountSecurityIndexRoute
  '/admin/organizations/$orgId/': typeof AdminOrganizationsOrgIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/app/clients/$clientId/': typeof AppClientsClientIdIndexRoute
  '/app/delivery-forms/$deliveryFormId/': typeof AppDeliveryFormsDeliveryFormIdIndexRoute
  '/app/invoices/$invoiceId/': typeof AppInvoicesInvoiceIdIndexRoute
  '/app/products/$productId/': typeof AppProductsProductIdIndexRoute
  '/app/purchase-orders/$purchaseOrderId/': typeof AppPurchaseOrdersPurchaseOrderIdIndexRoute
  '/app/quotations/$quotationId/': typeof AppQuotationsQuotationIdIndexRoute
  '/app/tickets/$ticketId/': typeof AppTicketsTicketIdIndexRoute
  '/auth/signin/otp/': typeof AuthSigninOtpIndexRoute
  '/orgs/$orgSlug/(navigation)/': typeof OrgsOrgSlugnavigationIndexRoute
  '/orgs/accept-invitation/$id/': typeof OrgsAcceptInvitationIdIndexRoute
  '/api/admin/organizations/$orgId/payments': typeof ApiAdminOrganizationsOrgIdPaymentsRoute
  '/(logged-in)/account/security/new-password/': typeof loggedInAccountSecurityNewPasswordIndexRoute
  '/orgs/$orgSlug/(navigation)/demo/': typeof OrgsOrgSlugnavigationDemoIndexRoute
  '/orgs/$orgSlug/(navigation)/settings/': typeof OrgsOrgSlugnavigationSettingsIndexRoute
  '/orgs/$orgSlug/(navigation)/settings/danger/': typeof OrgsOrgSlugnavigationSettingsDangerIndexRoute
  '/orgs/$orgSlug/(navigation)/settings/members/': typeof OrgsOrgSlugnavigationSettingsMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/orgs'
    | '/og.png'
    | '/robots.txt'
    | '/account'
    | '/app/clients'
    | '/app/delivery-forms'
    | '/app/insights'
    | '/app/invoices'
    | '/app/products'
    | '/app/purchase-orders'
    | '/app/quotations'
    | '/app/tickets'
    | '/orgs/$orgSlug'
    | '/admin/'
    | '/app/'
    | '/orgs/'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/app/delivery-forms/new'
    | '/app/invoices/new'
    | '/app/purchase-orders/new'
    | '/app/quotations/new'
    | '/app/tickets/new'
    | '/account/'
    | '/admin/organizations/'
    | '/admin/users/'
    | '/app/clients/'
    | '/app/delivery-forms/'
    | '/app/insights/'
    | '/app/invoices/'
    | '/app/products/'
    | '/app/purchase-orders/'
    | '/app/quotations/'
    | '/app/tickets/'
    | '/auth/confirm-delete/'
    | '/auth/forget-password/'
    | '/auth/goodbye/'
    | '/auth/new-user/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/verify/'
    | '/orgs/list/'
    | '/orgs/new/'
    | '/orgs/$orgSlug/settings'
    | '/account/change-email/'
    | '/account/change-password/'
    | '/account/danger/'
    | '/account/security/'
    | '/admin/organizations/$orgId/'
    | '/admin/users/$userId/'
    | '/app/clients/$clientId/'
    | '/app/delivery-forms/$deliveryFormId/'
    | '/app/invoices/$invoiceId/'
    | '/app/products/$productId/'
    | '/app/purchase-orders/$purchaseOrderId/'
    | '/app/quotations/$quotationId/'
    | '/app/tickets/$ticketId/'
    | '/auth/signin/otp/'
    | '/orgs/$orgSlug/'
    | '/orgs/accept-invitation/$id/'
    | '/api/admin/organizations/$orgId/payments'
    | '/account/security/new-password/'
    | '/orgs/$orgSlug/demo/'
    | '/orgs/$orgSlug/settings/'
    | '/orgs/$orgSlug/settings/danger/'
    | '/orgs/$orgSlug/settings/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/og.png'
    | '/robots.txt'
    | '/orgs/$orgSlug'
    | '/admin'
    | '/app'
    | '/orgs'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/app/delivery-forms/new'
    | '/app/invoices/new'
    | '/app/purchase-orders/new'
    | '/app/quotations/new'
    | '/app/tickets/new'
    | '/account'
    | '/admin/organizations'
    | '/admin/users'
    | '/app/clients'
    | '/app/delivery-forms'
    | '/app/insights'
    | '/app/invoices'
    | '/app/products'
    | '/app/purchase-orders'
    | '/app/quotations'
    | '/app/tickets'
    | '/auth/confirm-delete'
    | '/auth/forget-password'
    | '/auth/goodbye'
    | '/auth/new-user'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify'
    | '/orgs/list'
    | '/orgs/new'
    | '/account/change-email'
    | '/account/change-password'
    | '/account/danger'
    | '/account/security'
    | '/admin/organizations/$orgId'
    | '/admin/users/$userId'
    | '/app/clients/$clientId'
    | '/app/delivery-forms/$deliveryFormId'
    | '/app/invoices/$invoiceId'
    | '/app/products/$productId'
    | '/app/purchase-orders/$purchaseOrderId'
    | '/app/quotations/$quotationId'
    | '/app/tickets/$ticketId'
    | '/auth/signin/otp'
    | '/orgs/accept-invitation/$id'
    | '/api/admin/organizations/$orgId/payments'
    | '/account/security/new-password'
    | '/orgs/$orgSlug/demo'
    | '/orgs/$orgSlug/settings'
    | '/orgs/$orgSlug/settings/danger'
    | '/orgs/$orgSlug/settings/members'
  id:
    | '__root__'
    | '/'
    | '/(logged-in)'
    | '/admin'
    | '/app'
    | '/auth'
    | '/orgs'
    | '/og.png'
    | '/robots.txt'
    | '/(logged-in)/account'
    | '/app/clients'
    | '/app/delivery-forms'
    | '/app/insights'
    | '/app/invoices'
    | '/app/products'
    | '/app/purchase-orders'
    | '/app/quotations'
    | '/app/tickets'
    | '/orgs/$orgSlug'
    | '/admin/'
    | '/app/'
    | '/orgs/'
    | '/orgs/$orgSlug/(navigation)'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/app/delivery-forms/new'
    | '/app/invoices/new'
    | '/app/purchase-orders/new'
    | '/app/quotations/new'
    | '/app/tickets/new'
    | '/(logged-in)/account/'
    | '/admin/organizations/'
    | '/admin/users/'
    | '/app/clients/'
    | '/app/delivery-forms/'
    | '/app/insights/'
    | '/app/invoices/'
    | '/app/products/'
    | '/app/purchase-orders/'
    | '/app/quotations/'
    | '/app/tickets/'
    | '/auth/confirm-delete/'
    | '/auth/forget-password/'
    | '/auth/goodbye/'
    | '/auth/new-user/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/verify/'
    | '/orgs/list/'
    | '/orgs/new/'
    | '/orgs/$orgSlug/(navigation)/settings'
    | '/(logged-in)/account/change-email/'
    | '/(logged-in)/account/change-password/'
    | '/(logged-in)/account/danger/'
    | '/(logged-in)/account/security/'
    | '/admin/organizations/$orgId/'
    | '/admin/users/$userId/'
    | '/app/clients/$clientId/'
    | '/app/delivery-forms/$deliveryFormId/'
    | '/app/invoices/$invoiceId/'
    | '/app/products/$productId/'
    | '/app/purchase-orders/$purchaseOrderId/'
    | '/app/quotations/$quotationId/'
    | '/app/tickets/$ticketId/'
    | '/auth/signin/otp/'
    | '/orgs/$orgSlug/(navigation)/'
    | '/orgs/accept-invitation/$id/'
    | '/api/admin/organizations/$orgId/payments'
    | '/(logged-in)/account/security/new-password/'
    | '/orgs/$orgSlug/(navigation)/demo/'
    | '/orgs/$orgSlug/(navigation)/settings/'
    | '/orgs/$orgSlug/(navigation)/settings/danger/'
    | '/orgs/$orgSlug/(navigation)/settings/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  loggedInRouteRoute: typeof loggedInRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OrgsRouteRoute: typeof OrgsRouteRouteWithChildren
  OgDotpngRoute: typeof OgDotpngRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiAdminOrganizationsOrgIdPaymentsRoute: typeof ApiAdminOrganizationsOrgIdPaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.png': {
      id: '/og.png'
      path: '/og.png'
      fullPath: '/og.png'
      preLoaderRoute: typeof OgDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs': {
      id: '/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(logged-in)': {
      id: '/(logged-in)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof loggedInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/': {
      id: '/orgs/'
      path: '/'
      fullPath: '/orgs/'
      preLoaderRoute: typeof OrgsIndexRouteImport
      parentRoute: typeof OrgsRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/orgs/$orgSlug': {
      id: '/orgs/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof OrgsOrgSlugRouteRouteImport
      parentRoute: typeof OrgsRouteRoute
    }
    '/app/tickets': {
      id: '/app/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppTicketsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/quotations': {
      id: '/app/quotations'
      path: '/quotations'
      fullPath: '/app/quotations'
      preLoaderRoute: typeof AppQuotationsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/delivery-forms': {
      id: '/app/delivery-forms'
      path: '/delivery-forms'
      fullPath: '/app/delivery-forms'
      preLoaderRoute: typeof AppDeliveryFormsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(logged-in)/account': {
      id: '/(logged-in)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof loggedInAccountRouteRouteImport
      parentRoute: typeof loggedInRouteRoute
    }
    '/orgs/new/': {
      id: '/orgs/new/'
      path: '/new'
      fullPath: '/orgs/new/'
      preLoaderRoute: typeof OrgsNewIndexRouteImport
      parentRoute: typeof OrgsRouteRoute
    }
    '/orgs/list/': {
      id: '/orgs/list/'
      path: '/list'
      fullPath: '/orgs/list/'
      preLoaderRoute: typeof OrgsListIndexRouteImport
      parentRoute: typeof OrgsRouteRoute
    }
    '/auth/verify/': {
      id: '/auth/verify/'
      path: '/verify'
      fullPath: '/auth/verify/'
      preLoaderRoute: typeof AuthVerifyIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/signin'
      fullPath: '/auth/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/new-user/': {
      id: '/auth/new-user/'
      path: '/new-user'
      fullPath: '/auth/new-user/'
      preLoaderRoute: typeof AuthNewUserIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/goodbye/': {
      id: '/auth/goodbye/'
      path: '/goodbye'
      fullPath: '/auth/goodbye/'
      preLoaderRoute: typeof AuthGoodbyeIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forget-password/': {
      id: '/auth/forget-password/'
      path: '/forget-password'
      fullPath: '/auth/forget-password/'
      preLoaderRoute: typeof AuthForgetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/confirm-delete/': {
      id: '/auth/confirm-delete/'
      path: '/confirm-delete'
      fullPath: '/auth/confirm-delete/'
      preLoaderRoute: typeof AuthConfirmDeleteIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/tickets/': {
      id: '/app/tickets/'
      path: '/'
      fullPath: '/app/tickets/'
      preLoaderRoute: typeof AppTicketsIndexRouteImport
      parentRoute: typeof AppTicketsRouteRoute
    }
    '/app/quotations/': {
      id: '/app/quotations/'
      path: '/'
      fullPath: '/app/quotations/'
      preLoaderRoute: typeof AppQuotationsIndexRouteImport
      parentRoute: typeof AppQuotationsRouteRoute
    }
    '/app/purchase-orders/': {
      id: '/app/purchase-orders/'
      path: '/'
      fullPath: '/app/purchase-orders/'
      preLoaderRoute: typeof AppPurchaseOrdersIndexRouteImport
      parentRoute: typeof AppPurchaseOrdersRouteRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/invoices/': {
      id: '/app/invoices/'
      path: '/'
      fullPath: '/app/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppInvoicesRouteRoute
    }
    '/app/insights/': {
      id: '/app/insights/'
      path: '/'
      fullPath: '/app/insights/'
      preLoaderRoute: typeof AppInsightsIndexRouteImport
      parentRoute: typeof AppInsightsRouteRoute
    }
    '/app/delivery-forms/': {
      id: '/app/delivery-forms/'
      path: '/'
      fullPath: '/app/delivery-forms/'
      preLoaderRoute: typeof AppDeliveryFormsIndexRouteImport
      parentRoute: typeof AppDeliveryFormsRouteRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppClientsRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(logged-in)/account/': {
      id: '/(logged-in)/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof loggedInAccountIndexRouteImport
      parentRoute: typeof loggedInAccountRouteRoute
    }
    '/app/tickets/new': {
      id: '/app/tickets/new'
      path: '/new'
      fullPath: '/app/tickets/new'
      preLoaderRoute: typeof AppTicketsNewRouteImport
      parentRoute: typeof AppTicketsRouteRoute
    }
    '/app/quotations/new': {
      id: '/app/quotations/new'
      path: '/new'
      fullPath: '/app/quotations/new'
      preLoaderRoute: typeof AppQuotationsNewRouteImport
      parentRoute: typeof AppQuotationsRouteRoute
    }
    '/app/purchase-orders/new': {
      id: '/app/purchase-orders/new'
      path: '/new'
      fullPath: '/app/purchase-orders/new'
      preLoaderRoute: typeof AppPurchaseOrdersNewRouteImport
      parentRoute: typeof AppPurchaseOrdersRouteRoute
    }
    '/app/invoices/new': {
      id: '/app/invoices/new'
      path: '/new'
      fullPath: '/app/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppInvoicesRouteRoute
    }
    '/app/delivery-forms/new': {
      id: '/app/delivery-forms/new'
      path: '/new'
      fullPath: '/app/delivery-forms/new'
      preLoaderRoute: typeof AppDeliveryFormsNewRouteImport
      parentRoute: typeof AppDeliveryFormsRouteRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgSlug/(navigation)': {
      id: '/orgs/$orgSlug/(navigation)'
      path: ''
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof OrgsOrgSlugnavigationRouteRouteImport
      parentRoute: typeof OrgsOrgSlugRouteRoute
    }
    '/orgs/accept-invitation/$id/': {
      id: '/orgs/accept-invitation/$id/'
      path: '/accept-invitation/$id'
      fullPath: '/orgs/accept-invitation/$id/'
      preLoaderRoute: typeof OrgsAcceptInvitationIdIndexRouteImport
      parentRoute: typeof OrgsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/': {
      id: '/orgs/$orgSlug/(navigation)/'
      path: '/'
      fullPath: '/orgs/$orgSlug/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationRouteRoute
    }
    '/auth/signin/otp/': {
      id: '/auth/signin/otp/'
      path: '/signin/otp'
      fullPath: '/auth/signin/otp/'
      preLoaderRoute: typeof AuthSigninOtpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/tickets/$ticketId/': {
      id: '/app/tickets/$ticketId/'
      path: '/$ticketId'
      fullPath: '/app/tickets/$ticketId/'
      preLoaderRoute: typeof AppTicketsTicketIdIndexRouteImport
      parentRoute: typeof AppTicketsRouteRoute
    }
    '/app/quotations/$quotationId/': {
      id: '/app/quotations/$quotationId/'
      path: '/$quotationId'
      fullPath: '/app/quotations/$quotationId/'
      preLoaderRoute: typeof AppQuotationsQuotationIdIndexRouteImport
      parentRoute: typeof AppQuotationsRouteRoute
    }
    '/app/purchase-orders/$purchaseOrderId/': {
      id: '/app/purchase-orders/$purchaseOrderId/'
      path: '/$purchaseOrderId'
      fullPath: '/app/purchase-orders/$purchaseOrderId/'
      preLoaderRoute: typeof AppPurchaseOrdersPurchaseOrderIdIndexRouteImport
      parentRoute: typeof AppPurchaseOrdersRouteRoute
    }
    '/app/products/$productId/': {
      id: '/app/products/$productId/'
      path: '/$productId'
      fullPath: '/app/products/$productId/'
      preLoaderRoute: typeof AppProductsProductIdIndexRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/invoices/$invoiceId/': {
      id: '/app/invoices/$invoiceId/'
      path: '/$invoiceId'
      fullPath: '/app/invoices/$invoiceId/'
      preLoaderRoute: typeof AppInvoicesInvoiceIdIndexRouteImport
      parentRoute: typeof AppInvoicesRouteRoute
    }
    '/app/delivery-forms/$deliveryFormId/': {
      id: '/app/delivery-forms/$deliveryFormId/'
      path: '/$deliveryFormId'
      fullPath: '/app/delivery-forms/$deliveryFormId/'
      preLoaderRoute: typeof AppDeliveryFormsDeliveryFormIdIndexRouteImport
      parentRoute: typeof AppDeliveryFormsRouteRoute
    }
    '/app/clients/$clientId/': {
      id: '/app/clients/$clientId/'
      path: '/$clientId'
      fullPath: '/app/clients/$clientId/'
      preLoaderRoute: typeof AppClientsClientIdIndexRouteImport
      parentRoute: typeof AppClientsRouteRoute
    }
    '/admin/users/$userId/': {
      id: '/admin/users/$userId/'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AdminUsersUserIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations/$orgId/': {
      id: '/admin/organizations/$orgId/'
      path: '/organizations/$orgId'
      fullPath: '/admin/organizations/$orgId/'
      preLoaderRoute: typeof AdminOrganizationsOrgIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(logged-in)/account/security/': {
      id: '/(logged-in)/account/security/'
      path: '/security'
      fullPath: '/account/security/'
      preLoaderRoute: typeof loggedInAccountSecurityIndexRouteImport
      parentRoute: typeof loggedInAccountRouteRoute
    }
    '/(logged-in)/account/danger/': {
      id: '/(logged-in)/account/danger/'
      path: '/danger'
      fullPath: '/account/danger/'
      preLoaderRoute: typeof loggedInAccountDangerIndexRouteImport
      parentRoute: typeof loggedInAccountRouteRoute
    }
    '/(logged-in)/account/change-password/': {
      id: '/(logged-in)/account/change-password/'
      path: '/change-password'
      fullPath: '/account/change-password/'
      preLoaderRoute: typeof loggedInAccountChangePasswordIndexRouteImport
      parentRoute: typeof loggedInAccountRouteRoute
    }
    '/(logged-in)/account/change-email/': {
      id: '/(logged-in)/account/change-email/'
      path: '/change-email'
      fullPath: '/account/change-email/'
      preLoaderRoute: typeof loggedInAccountChangeEmailIndexRouteImport
      parentRoute: typeof loggedInAccountRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings': {
      id: '/orgs/$orgSlug/(navigation)/settings'
      path: '/settings'
      fullPath: '/orgs/$orgSlug/settings'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsRouteRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings/': {
      id: '/orgs/$orgSlug/(navigation)/settings/'
      path: '/'
      fullPath: '/orgs/$orgSlug/settings/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/demo/': {
      id: '/orgs/$orgSlug/(navigation)/demo/'
      path: '/demo'
      fullPath: '/orgs/$orgSlug/demo/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationDemoIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationRouteRoute
    }
    '/(logged-in)/account/security/new-password/': {
      id: '/(logged-in)/account/security/new-password/'
      path: '/security/new-password'
      fullPath: '/account/security/new-password/'
      preLoaderRoute: typeof loggedInAccountSecurityNewPasswordIndexRouteImport
      parentRoute: typeof loggedInAccountRouteRoute
    }
    '/api/admin/organizations/$orgId/payments': {
      id: '/api/admin/organizations/$orgId/payments'
      path: '/api/admin/organizations/$orgId/payments'
      fullPath: '/api/admin/organizations/$orgId/payments'
      preLoaderRoute: typeof ApiAdminOrganizationsOrgIdPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgSlug/(navigation)/settings/members/': {
      id: '/orgs/$orgSlug/(navigation)/settings/members/'
      path: '/members'
      fullPath: '/orgs/$orgSlug/settings/members/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsMembersIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings/danger/': {
      id: '/orgs/$orgSlug/(navigation)/settings/danger/'
      path: '/danger'
      fullPath: '/orgs/$orgSlug/settings/danger/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsDangerIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsRouteRoute
    }
  }
}

interface loggedInAccountRouteRouteChildren {
  loggedInAccountIndexRoute: typeof loggedInAccountIndexRoute
  loggedInAccountChangeEmailIndexRoute: typeof loggedInAccountChangeEmailIndexRoute
  loggedInAccountChangePasswordIndexRoute: typeof loggedInAccountChangePasswordIndexRoute
  loggedInAccountDangerIndexRoute: typeof loggedInAccountDangerIndexRoute
  loggedInAccountSecurityIndexRoute: typeof loggedInAccountSecurityIndexRoute
  loggedInAccountSecurityNewPasswordIndexRoute: typeof loggedInAccountSecurityNewPasswordIndexRoute
}

const loggedInAccountRouteRouteChildren: loggedInAccountRouteRouteChildren = {
  loggedInAccountIndexRoute: loggedInAccountIndexRoute,
  loggedInAccountChangeEmailIndexRoute: loggedInAccountChangeEmailIndexRoute,
  loggedInAccountChangePasswordIndexRoute:
    loggedInAccountChangePasswordIndexRoute,
  loggedInAccountDangerIndexRoute: loggedInAccountDangerIndexRoute,
  loggedInAccountSecurityIndexRoute: loggedInAccountSecurityIndexRoute,
  loggedInAccountSecurityNewPasswordIndexRoute:
    loggedInAccountSecurityNewPasswordIndexRoute,
}

const loggedInAccountRouteRouteWithChildren =
  loggedInAccountRouteRoute._addFileChildren(loggedInAccountRouteRouteChildren)

interface loggedInRouteRouteChildren {
  loggedInAccountRouteRoute: typeof loggedInAccountRouteRouteWithChildren
}

const loggedInRouteRouteChildren: loggedInRouteRouteChildren = {
  loggedInAccountRouteRoute: loggedInAccountRouteRouteWithChildren,
}

const loggedInRouteRouteWithChildren = loggedInRouteRoute._addFileChildren(
  loggedInRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminOrganizationsOrgIdIndexRoute: typeof AdminOrganizationsOrgIdIndexRoute
  AdminUsersUserIdIndexRoute: typeof AdminUsersUserIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminOrganizationsOrgIdIndexRoute: AdminOrganizationsOrgIdIndexRoute,
  AdminUsersUserIdIndexRoute: AdminUsersUserIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppClientsRouteRouteChildren {
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppClientsClientIdIndexRoute: typeof AppClientsClientIdIndexRoute
}

const AppClientsRouteRouteChildren: AppClientsRouteRouteChildren = {
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppClientsClientIdIndexRoute: AppClientsClientIdIndexRoute,
}

const AppClientsRouteRouteWithChildren = AppClientsRouteRoute._addFileChildren(
  AppClientsRouteRouteChildren,
)

interface AppDeliveryFormsRouteRouteChildren {
  AppDeliveryFormsNewRoute: typeof AppDeliveryFormsNewRoute
  AppDeliveryFormsIndexRoute: typeof AppDeliveryFormsIndexRoute
  AppDeliveryFormsDeliveryFormIdIndexRoute: typeof AppDeliveryFormsDeliveryFormIdIndexRoute
}

const AppDeliveryFormsRouteRouteChildren: AppDeliveryFormsRouteRouteChildren = {
  AppDeliveryFormsNewRoute: AppDeliveryFormsNewRoute,
  AppDeliveryFormsIndexRoute: AppDeliveryFormsIndexRoute,
  AppDeliveryFormsDeliveryFormIdIndexRoute:
    AppDeliveryFormsDeliveryFormIdIndexRoute,
}

const AppDeliveryFormsRouteRouteWithChildren =
  AppDeliveryFormsRouteRoute._addFileChildren(
    AppDeliveryFormsRouteRouteChildren,
  )

interface AppInsightsRouteRouteChildren {
  AppInsightsIndexRoute: typeof AppInsightsIndexRoute
}

const AppInsightsRouteRouteChildren: AppInsightsRouteRouteChildren = {
  AppInsightsIndexRoute: AppInsightsIndexRoute,
}

const AppInsightsRouteRouteWithChildren =
  AppInsightsRouteRoute._addFileChildren(AppInsightsRouteRouteChildren)

interface AppInvoicesRouteRouteChildren {
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppInvoicesInvoiceIdIndexRoute: typeof AppInvoicesInvoiceIdIndexRoute
}

const AppInvoicesRouteRouteChildren: AppInvoicesRouteRouteChildren = {
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppInvoicesInvoiceIdIndexRoute: AppInvoicesInvoiceIdIndexRoute,
}

const AppInvoicesRouteRouteWithChildren =
  AppInvoicesRouteRoute._addFileChildren(AppInvoicesRouteRouteChildren)

interface AppProductsRouteRouteChildren {
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppProductsProductIdIndexRoute: typeof AppProductsProductIdIndexRoute
}

const AppProductsRouteRouteChildren: AppProductsRouteRouteChildren = {
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppProductsProductIdIndexRoute: AppProductsProductIdIndexRoute,
}

const AppProductsRouteRouteWithChildren =
  AppProductsRouteRoute._addFileChildren(AppProductsRouteRouteChildren)

interface AppPurchaseOrdersRouteRouteChildren {
  AppPurchaseOrdersNewRoute: typeof AppPurchaseOrdersNewRoute
  AppPurchaseOrdersIndexRoute: typeof AppPurchaseOrdersIndexRoute
  AppPurchaseOrdersPurchaseOrderIdIndexRoute: typeof AppPurchaseOrdersPurchaseOrderIdIndexRoute
}

const AppPurchaseOrdersRouteRouteChildren: AppPurchaseOrdersRouteRouteChildren =
  {
    AppPurchaseOrdersNewRoute: AppPurchaseOrdersNewRoute,
    AppPurchaseOrdersIndexRoute: AppPurchaseOrdersIndexRoute,
    AppPurchaseOrdersPurchaseOrderIdIndexRoute:
      AppPurchaseOrdersPurchaseOrderIdIndexRoute,
  }

const AppPurchaseOrdersRouteRouteWithChildren =
  AppPurchaseOrdersRouteRoute._addFileChildren(
    AppPurchaseOrdersRouteRouteChildren,
  )

interface AppQuotationsRouteRouteChildren {
  AppQuotationsNewRoute: typeof AppQuotationsNewRoute
  AppQuotationsIndexRoute: typeof AppQuotationsIndexRoute
  AppQuotationsQuotationIdIndexRoute: typeof AppQuotationsQuotationIdIndexRoute
}

const AppQuotationsRouteRouteChildren: AppQuotationsRouteRouteChildren = {
  AppQuotationsNewRoute: AppQuotationsNewRoute,
  AppQuotationsIndexRoute: AppQuotationsIndexRoute,
  AppQuotationsQuotationIdIndexRoute: AppQuotationsQuotationIdIndexRoute,
}

const AppQuotationsRouteRouteWithChildren =
  AppQuotationsRouteRoute._addFileChildren(AppQuotationsRouteRouteChildren)

interface AppTicketsRouteRouteChildren {
  AppTicketsNewRoute: typeof AppTicketsNewRoute
  AppTicketsIndexRoute: typeof AppTicketsIndexRoute
  AppTicketsTicketIdIndexRoute: typeof AppTicketsTicketIdIndexRoute
}

const AppTicketsRouteRouteChildren: AppTicketsRouteRouteChildren = {
  AppTicketsNewRoute: AppTicketsNewRoute,
  AppTicketsIndexRoute: AppTicketsIndexRoute,
  AppTicketsTicketIdIndexRoute: AppTicketsTicketIdIndexRoute,
}

const AppTicketsRouteRouteWithChildren = AppTicketsRouteRoute._addFileChildren(
  AppTicketsRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppClientsRouteRoute: typeof AppClientsRouteRouteWithChildren
  AppDeliveryFormsRouteRoute: typeof AppDeliveryFormsRouteRouteWithChildren
  AppInsightsRouteRoute: typeof AppInsightsRouteRouteWithChildren
  AppInvoicesRouteRoute: typeof AppInvoicesRouteRouteWithChildren
  AppProductsRouteRoute: typeof AppProductsRouteRouteWithChildren
  AppPurchaseOrdersRouteRoute: typeof AppPurchaseOrdersRouteRouteWithChildren
  AppQuotationsRouteRoute: typeof AppQuotationsRouteRouteWithChildren
  AppTicketsRouteRoute: typeof AppTicketsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppClientsRouteRoute: AppClientsRouteRouteWithChildren,
  AppDeliveryFormsRouteRoute: AppDeliveryFormsRouteRouteWithChildren,
  AppInsightsRouteRoute: AppInsightsRouteRouteWithChildren,
  AppInvoicesRouteRoute: AppInvoicesRouteRouteWithChildren,
  AppProductsRouteRoute: AppProductsRouteRouteWithChildren,
  AppPurchaseOrdersRouteRoute: AppPurchaseOrdersRouteRouteWithChildren,
  AppQuotationsRouteRoute: AppQuotationsRouteRouteWithChildren,
  AppTicketsRouteRoute: AppTicketsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthConfirmDeleteIndexRoute: typeof AuthConfirmDeleteIndexRoute
  AuthForgetPasswordIndexRoute: typeof AuthForgetPasswordIndexRoute
  AuthGoodbyeIndexRoute: typeof AuthGoodbyeIndexRoute
  AuthNewUserIndexRoute: typeof AuthNewUserIndexRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthVerifyIndexRoute: typeof AuthVerifyIndexRoute
  AuthSigninOtpIndexRoute: typeof AuthSigninOtpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthConfirmDeleteIndexRoute: AuthConfirmDeleteIndexRoute,
  AuthForgetPasswordIndexRoute: AuthForgetPasswordIndexRoute,
  AuthGoodbyeIndexRoute: AuthGoodbyeIndexRoute,
  AuthNewUserIndexRoute: AuthNewUserIndexRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthVerifyIndexRoute: AuthVerifyIndexRoute,
  AuthSigninOtpIndexRoute: AuthSigninOtpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OrgsOrgSlugnavigationSettingsRouteRouteChildren {
  OrgsOrgSlugnavigationSettingsIndexRoute: typeof OrgsOrgSlugnavigationSettingsIndexRoute
  OrgsOrgSlugnavigationSettingsDangerIndexRoute: typeof OrgsOrgSlugnavigationSettingsDangerIndexRoute
  OrgsOrgSlugnavigationSettingsMembersIndexRoute: typeof OrgsOrgSlugnavigationSettingsMembersIndexRoute
}

const OrgsOrgSlugnavigationSettingsRouteRouteChildren: OrgsOrgSlugnavigationSettingsRouteRouteChildren =
  {
    OrgsOrgSlugnavigationSettingsIndexRoute:
      OrgsOrgSlugnavigationSettingsIndexRoute,
    OrgsOrgSlugnavigationSettingsDangerIndexRoute:
      OrgsOrgSlugnavigationSettingsDangerIndexRoute,
    OrgsOrgSlugnavigationSettingsMembersIndexRoute:
      OrgsOrgSlugnavigationSettingsMembersIndexRoute,
  }

const OrgsOrgSlugnavigationSettingsRouteRouteWithChildren =
  OrgsOrgSlugnavigationSettingsRouteRoute._addFileChildren(
    OrgsOrgSlugnavigationSettingsRouteRouteChildren,
  )

interface OrgsOrgSlugnavigationRouteRouteChildren {
  OrgsOrgSlugnavigationSettingsRouteRoute: typeof OrgsOrgSlugnavigationSettingsRouteRouteWithChildren
  OrgsOrgSlugnavigationIndexRoute: typeof OrgsOrgSlugnavigationIndexRoute
  OrgsOrgSlugnavigationDemoIndexRoute: typeof OrgsOrgSlugnavigationDemoIndexRoute
}

const OrgsOrgSlugnavigationRouteRouteChildren: OrgsOrgSlugnavigationRouteRouteChildren =
  {
    OrgsOrgSlugnavigationSettingsRouteRoute:
      OrgsOrgSlugnavigationSettingsRouteRouteWithChildren,
    OrgsOrgSlugnavigationIndexRoute: OrgsOrgSlugnavigationIndexRoute,
    OrgsOrgSlugnavigationDemoIndexRoute: OrgsOrgSlugnavigationDemoIndexRoute,
  }

const OrgsOrgSlugnavigationRouteRouteWithChildren =
  OrgsOrgSlugnavigationRouteRoute._addFileChildren(
    OrgsOrgSlugnavigationRouteRouteChildren,
  )

interface OrgsOrgSlugRouteRouteChildren {
  OrgsOrgSlugnavigationRouteRoute: typeof OrgsOrgSlugnavigationRouteRouteWithChildren
}

const OrgsOrgSlugRouteRouteChildren: OrgsOrgSlugRouteRouteChildren = {
  OrgsOrgSlugnavigationRouteRoute: OrgsOrgSlugnavigationRouteRouteWithChildren,
}

const OrgsOrgSlugRouteRouteWithChildren =
  OrgsOrgSlugRouteRoute._addFileChildren(OrgsOrgSlugRouteRouteChildren)

interface OrgsRouteRouteChildren {
  OrgsOrgSlugRouteRoute: typeof OrgsOrgSlugRouteRouteWithChildren
  OrgsIndexRoute: typeof OrgsIndexRoute
  OrgsListIndexRoute: typeof OrgsListIndexRoute
  OrgsNewIndexRoute: typeof OrgsNewIndexRoute
  OrgsAcceptInvitationIdIndexRoute: typeof OrgsAcceptInvitationIdIndexRoute
}

const OrgsRouteRouteChildren: OrgsRouteRouteChildren = {
  OrgsOrgSlugRouteRoute: OrgsOrgSlugRouteRouteWithChildren,
  OrgsIndexRoute: OrgsIndexRoute,
  OrgsListIndexRoute: OrgsListIndexRoute,
  OrgsNewIndexRoute: OrgsNewIndexRoute,
  OrgsAcceptInvitationIdIndexRoute: OrgsAcceptInvitationIdIndexRoute,
}

const OrgsRouteRouteWithChildren = OrgsRouteRoute._addFileChildren(
  OrgsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  loggedInRouteRoute: loggedInRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OrgsRouteRoute: OrgsRouteRouteWithChildren,
  OgDotpngRoute: OgDotpngRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiAdminOrganizationsOrgIdPaymentsRoute:
    ApiAdminOrganizationsOrgIdPaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
